### PR TITLE
Does it work on Python 3.9?

### PR DESCRIPTION
**Pull request by ecomodeller**

### CODE REVIEW

**Comment by ecomodeller** [comment]
@AurelienDHI wants to use mikeio1d in a QGIS [plugin](https://github.com/DHI/qgis-res1d-plugin) and QGIS 3.22 apparently bundles Python 3.9

**Comment by ecomodeller** [comment]
Apparently needs something else on a fresh machine
image

**Comment by gedaskir** [comment]
As far as I know pythonnet does not support Python 3.9 yet (as of 2021-11-09). See for example, https://github.com/pythonnet/pythonnet/issues/1262

**Comment by ecomodeller** [comment]
> As far as I know pythonnet does not support Python 3.9 yet (as of 2021-11-09). See for example, [pythonnet/pythonnet#1262](https://github.com/pythonnet/pythonnet/issues/1262)

It is missing a wheel for 3.9 https://pypi.org/project/pythonnet/#files

But apparently it can be done 
image
if the necessary dependencies are in place (build tools).

**Pull request closed without merging**
